name: ArduinoBuild

env:
  SKETCH_NAME: build_test.ino

on:
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**ArduinoBuild.yml'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{matrix.board}}@${{matrix.platform-version}}

    runs-on: ubuntu-latest

    strategy:
      matrix:

        platform-url:
          - https://espressif.github.io/arduino-esp32/package_esp32_index.json

        board:
          # ESP32 devices for 3D matrix
          - esp32
          - esp32s2
          - esp32s3
          - esp32c3
          - esp32p4
          - m5stick-c
          - m5stack-core-esp32
          - m5stack-core2

        platform-version:
          # ESP32 Core versions for 3D matrix
          - 2.0.15
          - 2.0.16
          - 2.0.17

        include:
          - { board: esp32,    platform: esp32, platform-version: latest, platform-url: 'https://espressif.github.io/arduino-esp32/package_esp32_index.json', archi: esp32, ... }
          - { board: esp32s2,  platform: esp32, platform-version: latest, platform-url: 'https://espressif.github.io/arduino-esp32/package_esp32_index.json', archi: esp32, ... }
          - { board: esp32s3,  platform: esp32, platform-version: latest, platform-url: 'https://espressif.github.io/arduino-esp32/package_esp32_index.json', archi: esp32, ... }
          - { board: esp32c3,  platform: esp32, platform-version: latest, platform-url: 'https://espressif.github.io/arduino-esp32/package_esp32_index.json', archi: esp32, ... }
          - { board: esp32c6,  platform: esp32, platform-version: latest, platform-url: 'https://espressif.github.io/arduino-esp32/package_esp32_index.json', archi: esp32, ... }
          - { board: esp32p4,  platform: esp32, platform-version: latest, platform-url: 'https://espressif.github.io/arduino-esp32/package_esp32_index.json', archi: esp32, ... }

          # 3D matrix applies to these:
          - { platform: esp32, archi: esp32, ... }

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Compile example
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: ${{matrix.platform}}:${{matrix.archi}}:${{matrix.board}}
          arduino-platform: ${{matrix.platform}}:${{matrix.archi}}@${{matrix.platform-version}}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ matrix.required-libraries }}
          extra-arduino-cli-args: ${{ matrix.cli-args }}
          sketch-names: ${{ env.SKETCH_NAME }}
